### ISSUE TITLE
HttpClient injection

### ISSUE THREAD

**Issue by AmbroiseCouissin** [Xignite/DotNetSDK#4]
Hi,

As it is, the library is pretty hard to mock correctly as we can't inject the HttpClient. It would be great if you could give us that option. Thanks.

Ambroise

**Comment by awalsh128** [comment]
Hi Ambroise,

We can provide an interface in a future release for you to mock the client. The request and response objects will probably need to be wrappers around the System.[Net.Http,Web] equivalents since they didn't really design them for mocking. I will update the issue when we have something to release.

**Comment by AmbroiseCouissin** [comment]
An interface will do.

Actually the HttpMessageHandler in the HttpClient is mocked easily. 

Also, the reuse of HttpClient multiplies performance and is something that should be done perfectly. Or you can give the option of injecting it so that we can use it like we want for mocking or for generating it from the IoC container.

You can have a good example from salesforce SDK for .net.

Thanks

**Comment by awalsh128** [comment]
Version 1.0.5.0 has been released which allows you to mock the web services via its interfaces or change the HttpMessageHandler behavior.

Thanks for your feedback. We currently observe HttpClient best practices in previous versions. Most importantly, the use of a shared object among many callers.

**Comment by AmbroiseCouissin** [comment]
Thanks a lot!

For HttpClient, I believe that the best way is to give the option for us to inject the HttpClient. And to give a default if not injected. You can just put the HttpClient as an optional attribute in the constructors. Or you can overload your constructors with an HttpClient attribute.

Sometimes people want to use a separate HttpClient per uri, or per request, or share an HttpClient among all the calls.

Giving the option is easy to implement and very cool to have so that we can command the generation and lifecycle of the HttpClient from the IoC.

Thanks
