### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by edwardwilson** [Xignite/DotNetSDK#5]
I cannot find any documentation which explains the possible return types of any of the SDK methods and most importantly what exceptions could be thrown from any call.

Does this exist? If the SDK code was open sourced we could figure it out our selfs; without it really needs to be documented!

**Comment by cstupi** [comment]
The possible return types are included in the dll. 
The calls would throw exceptions listed under new Xignite.Sdk.Exceptions.

The SDK is a simple wrapper around web calls and would serve little purpose to open source.
