### ISSUE TITLE
GlobalHistorical GetAllCashDividendsByExchange uses ExchangeType

### ISSUE THREAD

**Issue by dbasilio** [Xignite/DotNetSDK#6]
We want to pull all the dividends by the market identification code, but the api is using ExchangeType which is an enum. Is there a way to may market identification codes to ExchangeType. Otherwise we have to send one request per symbol.

**Comment by yuqin99** [comment]
This a limitation of this API (not the SDK).  Please contact support@xignite.com so they can provide you some workaround based on your use case.
